logging:
  level:
    sql: debug

spring:
  datasource:
    url: ***REMOVED***
    username: marketplace_admin
    password: ***REMOVED***
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ***REMOVED***
        credential:
          client-id: ***REMOVED***
          client-secret: ***REMOVED***
        app-id-uri: api://***REMOVED***

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
