logging:
  level:
    sql: debug

spring:
  datasource:
    url: ***REMOVED***
    username: marketplace_admin
    password: ***REMOVED***
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ***REMOVED***
        credential:
          client-id: ***REMOVED***
          client-secret: ***REMOVED***
        app-id-uri: api://***REMOVED***
      storage:
        account-name: endavamarketplaceimages
        account-key: ***REMOVED***
        endpoint: ***REMOVED***
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
